# Generated by Django 3.2.13 on 2022-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(1, 'graphics'), (2, 'web Development'), (3, 'in Development')], default=3, null=True)),
                ('name', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs_img')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills_img'),
        ),
    ]
